######################################################################
# Automatically generated by qmake (2.01a) Tue Jul 10 14:25:26 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES +=  quit.cc
