// ========================================================================
// Program ATTRIBUTE_IMAGES is a variant of VIEWIMAGES.  It can be
// used to assign attributes such as gender to a set of images
// annotated with bounding boxes by Davis King's IMGLAB tool.  Face
// bbox information is converted via program XML2TXT into a format
// which can be integested by this progrma.  ATTRIBUTE_IMAGES also
// takes a text file generated by program IMAGE_SIZES containing pixel
// width and height for each image to be attributed.

// Given an image, ATTRIBUTE_IMAGES dymamically instantiates and
// displays OSG rectangular PolyLines around previously-annotated
// faces.  By default, XML2TXT assigns all attributes to "unset"
// values.  The user may press "1", "2" or "0" on the number pad in
// order to reset gender attributes for all bboxes in the current
// image to male, female or unknown.  After an individual bbox is
// selected via the mouse, its gender attribute may be changed to
// male, female or unknown by pressing the "1", "2" and "~" keys near
// the upper left corner of the keyboard.

// ATTRIBUTE_IMAGES can scan through all image files contained within
// the present working directory.  If all the input image files do not
// have uniform pixel size, borders are dynamically added as necessary
// to each input image so that effectively all images end up with the
// same pixel widths and heights.  To minimize the need for
// user-zooming, ATTRIBUTE_IMAGES also attempts to display each new
// image in similar-sized 2D OSG windows.

// ATTRIBUTE_IMAGES exports an updated text file each time an
// attribute of a face bbox is altered.

//			./attribute_images

// ========================================================================
// Last updated on 7/5/16; 7/6/16; 7/7/16; 7/22/16
// ========================================================================

#include <fstream>
#include <iostream>
#include <map>
#include <set>
#include <string>
#include <vector>

#include "osg/osgGraphicals/AnimationController.h"
#include "osg/osgGraphicals/CentersGroup.h"
#include "osg/osgGraphicals/CenterPickHandler.h"
#include "astro_geo/Clock.h"
#include "osg/Custom2DManipulator.h"
#include "osg/osgOrganization/Decorations.h"
#include "image/imagefuncs.h"
#include "osg/osg2D/ImageNumberHUD.h"
#include "osg/ModeController.h"
#include "osg/osg2D/MoviesGroup.h"
#include "osg/osg2D/MovieKeyHandler.h"
#include "osg/osgOperations/Operations.h"
#include "passes/PassesGroup.h"
#include "osg/osgGeometry/PolygonsGroup.h"
#include "osg/osgGeometry/PolyLinesGroup.h"
#include "time/timefuncs.h"
#include "osg/osgWindow/ViewerManager.h"

// ========================================================================
int main( int argc, char** argv )
{
   using std::cin;
   using std::cout;
   using std::endl;
   using std::map;
   using std::pair;
   using std::string;
   using std::vector;

   timefunc::initialize_timeofday_clock(); 
   std::set_new_handler(sysfunc::out_of_memory);

   bool ignore_hands_flag = true;

   string faces_rootdir = "/data/TrainingImagery/faces/";
   string labeled_faces_subdir = faces_rootdir + "images/";
   string bbox_labels_filename = labeled_faces_subdir+
      "labeled_face_hand_bboxes.txt";
   if(ignore_hands_flag)
   {
      bbox_labels_filename = labeled_faces_subdir+"labeled_face_bboxes.txt";
   }
   filefunc::ReadInfile(bbox_labels_filename);

   typedef map<string, vector<bounding_box> > ANNOTATED_BBOXES_MAP;
// independent string: image_ID_str
// dependent STL vector: annotated bboxes

   ANNOTATED_BBOXES_MAP annotated_bboxes_map;
   ANNOTATED_BBOXES_MAP::iterator annotated_bboxes_iter;

   typedef map<int, pair<string, int> > OSG_BBOXES_MAP;
// independent int: OSG PolyLine ID
// dependent pair:  string = image_ID_str, int = curr image bbox index

   OSG_BBOXES_MAP osg_bboxes_map;

   bool first_image_flag = true;
   string image_ID_str = "";
   vector<bounding_box> annotated_bboxes;
   for(unsigned int i = 0; i < filefunc::text_line.size(); i++)
   {
      string curr_line=filefunc::text_line[i];

      vector<string> substrings = stringfunc::decompose_string_into_substrings(
         curr_line);
      if(substrings[0] == "Image:")
      {
         if(first_image_flag)
         {
            first_image_flag = false;
         }
         else
         {
            // Save previous image info into data structures
            annotated_bboxes_map[image_ID_str] = annotated_bboxes;
            annotated_bboxes.clear();
         }
         annotated_bboxes.clear();
         image_ID_str = substrings[6];
      }
      else
      {
         vector<string> substrings = 
            stringfunc::decompose_string_into_substrings(curr_line);
         string bbox_label = substrings[1];
         int px_min = stringfunc::string_to_number(substrings[2]);
         int px_max = stringfunc::string_to_number(substrings[3]);
         int py_min = stringfunc::string_to_number(substrings[4]);
         int py_max = stringfunc::string_to_number(substrings[5]);
         bounding_box curr_bbox(px_min, px_max, py_min, py_max);

         colorfunc::Color bbox_color = colorfunc::black;
         if(bbox_label == "face")
         {
//            bbox_color = colorfunc::orange;
            bbox_color = colorfunc::red;
         }
         else if(bbox_label == "hand")
         {
//            bbox_color = colorfunc::yegr;
            bbox_color = colorfunc::cyan;
         }

         curr_bbox.set_label(bbox_label);
         curr_bbox.set_color(bbox_color);

// Search for any bbox attribute key-value pairs:

         int n_attribute_pairs = (substrings.size() - 6)/2;
         for(int ap = 0; ap < n_attribute_pairs; ap++)
         {
            string attr_key = substrings[6 + ap * 2];
            string attr_value = substrings[6 + ap * 2 + 1];
            curr_bbox.set_attribute_value(attr_key, attr_value);
         }

// As of 7/7/16, we initialize ID for each new bbox to -1.  When a
// PolyLine corresponding to a bbox is generated, its ID is reset to
// the PolyLine's ID:

         curr_bbox.set_ID(-1);

         annotated_bboxes.push_back(curr_bbox);
//         cout << annotated_bboxes.back() << endl;

      } // substrings[0] == "Image:" conditional
   } // loop over index i labeling lines in detections text file

   // Save final image info into data structures
   annotated_bboxes_map[image_ID_str] = annotated_bboxes;

// Parse text file generated by program IMAGE_SIZES and store xdim,
// ydim values within STL map.  Find maximum pixel width and height
// among all input images:

   typedef map<string, pair<int, int> > IMAGE_SIZES_MAP;
// independent int: image_ID_str
// dependent pair:  xdim, ydim

   IMAGE_SIZES_MAP image_sizes_map;
   IMAGE_SIZES_MAP::iterator image_sizes_iter;

   string image_sizes_filename=labeled_faces_subdir+"image_sizes.dat";
   filefunc::ReadInfile(image_sizes_filename);
   int max_image_width = 0, max_image_height = 0;
   for (unsigned int i=0; i<filefunc::text_line.size(); i++)
   {
      vector<string> substrings = stringfunc::decompose_string_into_substrings(
         filefunc::text_line[i]);
      string image_basename=substrings[0];
      string image_ID_str = image_basename.substr(6,5);

      int xdim = stringfunc::string_to_number(substrings[1]);
      int ydim = stringfunc::string_to_number(substrings[2]);
      pair<int, int> P;
      P.first = xdim;
      P.second = ydim;
      image_sizes_map[image_ID_str] = P;

      max_image_width = basic_math::max(max_image_width, xdim);
      max_image_height = basic_math::max(max_image_height, ydim);
   }
   cout << "max_image_width = " << max_image_width
        << " max_image_height = " << max_image_height << endl;

// Use an ArgumentParser object to manage the program arguments:

   osg::ArgumentParser arguments(&argc,argv);

// Initialize constants and parameters read in from command line as
// well as ascii text file:

   const int ndims=2;
   PassesGroup passes_group(&arguments);
   int videopass_ID=passes_group.get_videopass_ID();
   cout << "videopass_ID = " << videopass_ID << endl;

// Construct the viewer and instantiate a ViewerManager:

   WindowManager* window_mgr_ptr=new ViewerManager();
   window_mgr_ptr->initialize_window("2D imagery");

// Create OSG root node:

   osg::Group* root = new osg::Group;

// Instantiate Operations object to handle mode, animation and image
// number control:

   bool display_movie_state=true;
   bool display_movie_number=true;
   bool display_movie_world_time=false;
   bool display_movie_elapsed_time=false;
   bool hide_Mode_HUD_flag = false;
   bool display_movie_nframes=true;

   Operations operations(
      ndims,window_mgr_ptr,passes_group,display_movie_state,
      display_movie_number,display_movie_world_time,
      display_movie_elapsed_time, hide_Mode_HUD_flag,
      display_movie_nframes);

   ModeController* ModeController_ptr=operations.get_ModeController_ptr();
//   ModeController_ptr->setState(ModeController::RUN_MOVIE);
   ModeController_ptr->setState(ModeController::MANIPULATE_POLYLINE);
   AnimationController* AnimationController_ptr=
      operations.get_AnimationController_ptr();
   root->addChild(operations.get_OSGgroup_ptr());

// Add a custom manipulator to the event handler list:

   osgGA::Custom2DManipulator* CM_2D_ptr = 
      new osgGA::Custom2DManipulator(ModeController_ptr,window_mgr_ptr);
   window_mgr_ptr->set_CameraManipulator(CM_2D_ptr);

// Instantiate group to hold all decorations:
   
   Decorations decorations(window_mgr_ptr,ModeController_ptr,CM_2D_ptr);

// Instantiate PolyLines decorations group:

   PolyLinesGroup* PolyLinesGroup_ptr= decorations.add_PolyLines(
      ndims,passes_group.get_pass_ptr(videopass_ID), AnimationController_ptr);
   PolyLinesGroup_ptr->set_CM_2D_ptr(CM_2D_ptr);
   PolyLinesGroup_ptr->set_erase_Graphicals_except_at_curr_time_flag(true);
   PolyLinesGroup_ptr->set_annotated_bboxes_map_ptr(&annotated_bboxes_map);
   PolyLinesGroup_ptr->set_osg_bboxes_map_ptr(&osg_bboxes_map);
   PolyLinesGroup_ptr->set_image_sizes_map_ptr(&image_sizes_map);
   PolyLinesGroup_ptr->set_max_image_dims(max_image_width, max_image_height);
   PolyLinesGroup_ptr->set_bbox_labels_filename(bbox_labels_filename);
   PolyLinesGroup_ptr->set_attribute_key("gender");

// Instantiate group to hold movie:

   MoviesGroup movies_group(
      ndims,passes_group.get_pass_ptr(videopass_ID),
      decorations.get_PointsGroup_ptr(),
      decorations.get_PolygonsGroup_ptr(),
      AnimationController_ptr);

   string images_subdir="./";
   AnimationController_ptr->store_unordered_image_filenames(images_subdir);
   int Nimages=AnimationController_ptr->get_n_ordered_image_filenames();
   cout << "Nimages = " << Nimages << endl;

   texture_rectangle *texture_rectangle_ptr = new texture_rectangle(
      max_image_width, max_image_height, 1, 4, AnimationController_ptr);
   Movie* movie_ptr=movies_group.generate_new_Movie(texture_rectangle_ptr);

   AnimationController_ptr->set_nframes(Nimages);
   movie_ptr->get_texture_rectangle_ptr()->set_first_frame_to_display(0);
   movie_ptr->get_texture_rectangle_ptr()->set_last_frame_to_display(
      Nimages-1);
   root->addChild( movies_group.get_OSGgroup_ptr() );

   MovieKeyHandler* MoviesKeyHandler_ptr=
      new MovieKeyHandler(ModeController_ptr,&movies_group);
   window_mgr_ptr->get_EventHandlers_ptr()->push_back(MoviesKeyHandler_ptr);

   PolyLinesGroup_ptr->set_erase_Graphicals_except_at_curr_time_flag(true);

// Generate PolyLines corresponding to bounding boxes in first image:

   string curr_image_filename=
      AnimationController_ptr->get_curr_image_filename();
   vector<string> substrings = 
      stringfunc::decompose_string_into_substrings(
         curr_image_filename,"_.");
   image_ID_str = substrings[1];
   PolyLinesGroup_ptr->generate_image_bboxes(image_ID_str);

   PolyLinesGroup_ptr->count_bbox_attributes();

   cout << endl;
   cout << "******************************************************" << endl;
   cout << "Keyboard control notes:" << endl << endl;
   cout << "Note: Image window must be active before following keys will be recognized" 
        << endl << endl;
   cout << "'p' key toggles image player between 'play' and 'pause' modes " 
        << endl;
   cout << "'r' key reverses image's time direction" << endl;
   cout << "Right and left arrow keys step one image frame forward/backward"
        << endl;
   cout << "'a' key allows user to enter an annotation for current frame"
        << endl;
   cout << "'e' key exports all image annotations to output CSV file" 
        << endl;
   cout << "spacebar 'homes' image window to default settings" << endl;
   cout << endl;
   cout << "******************************************************" << endl;
   cout << "Mouse control notes:" << endl << endl;
   cout << "Left mouse button translates image frame in 2D" << endl;
   cout << "Center mouse button rotates image window in 2D" << endl;
   cout << "Right mouse button zooms image frame in/out" << endl;
   cout << "******************************************************" << endl;
   cout << endl;

   decorations.set_DataNode_ptr(movie_ptr->getGeode());

   root->addChild(decorations.get_OSGgroup_ptr());

// Attach the scene graph to the viewer:

   window_mgr_ptr->setSceneData(root);

// Create the windows and run the threads.  Viewer's realize method
// calls the CustomManipulator's home() method:

   window_mgr_ptr->realize();

   while( !window_mgr_ptr->done() )
   {
      window_mgr_ptr->process();
   }
}

