 // ========================================================================
// Program EXTRACT_FLIPFRAMES utilizes FFMPEG to decompose an input
// Flip .mp4 file into individual JPG frames.

//				extract_flipframes

// ========================================================================
// Last updated on 8/15/10; 8/28/10; 9/20/10
// ========================================================================

#include <iostream>
#include <string>

#include "general/filefuncs.h"
#include "general/outputfuncs.h"
#include "general/stringfuncs.h"
#include "general/sysfuncs.h"

using std::cin;
using std::cout;
using std::endl;
using std::ofstream;
using std::string;

// ==========================================================================
int main( int argc, char** argv )
{
   sysfunc::clearscreen();

   string Flip_movies_subdir="/data/tech_challenge/flip_movies/";
   cout << "Program EXTRACT_FLIPFRAMES expects to find .mp4 movies"
        << endl;
   cout << "generated by a Flip video cameras sitting within " << endl;
   cout << Flip_movies_subdir << endl << endl;

   string Flip_mp4_filename;
   cout << "Enter input Flip camera's .mp4 filename:" << endl << endl;
   cin >> Flip_mp4_filename;

   string Flip_filename_prefix=stringfunc::prefix(Flip_mp4_filename);
   Flip_mp4_filename=Flip_movies_subdir+Flip_mp4_filename;

   cout << endl;
   if (filefunc::fileexist(Flip_mp4_filename))
   {
      cout << "Input Flip video camera's MP4 movie found" << endl;
   }
   else
   {
      cout << "No Flip video camera MP4 movie found" << endl;
      cout << "within "+Flip_mp4_filename << endl << endl;
      cout << "Program EXTRACT_FLIPFRAMES is now exiting..." << endl << endl;
      exit(-1);
   }
   
   string output_subdir=Flip_movies_subdir+Flip_filename_prefix+
	"_jpg_frames/";
   cout << "Program EXTRACT_FLIPFRAMES will convert MP4 movies into a"
        << endl;
   cout << "sequence of JPEG images which will be written to "+output_subdir 
        << endl << endl;

   outputfunc::enter_continue_char();

   filefunc::dircreate(output_subdir);

   string unix_cmd=
      "ffmpeg -i "+Flip_mp4_filename+
      " -sameq -r 2 "+output_subdir+"image-%05d.jpg";
//      " -sameq -r 10 "+output_subdir+"image-%05d.jpg";
//      " -r 5 "+output_subdir+"image-%05d.png";

   cout << "unix_cmd = " << unix_cmd << endl;
   sysfunc::unix_command(unix_cmd);
}


//   ./ffmpeg -i in.avi -vf "crop=0:0:0:240" out.avi

// -sameq

// -qscale 1
