#ifndef KERNEL_PORT_DATA_TYPE_H
#define KERNEL_PORT_DATA_TYPE_H

enum KernelPortDataType
{
	KERNEL_PORT_DATA_TYPE_NULL, // no data, comparison always false

	KERNEL_PORT_DATA_TYPE_BOOL,
	KERNEL_PORT_DATA_TYPE_FLOAT,
	KERNEL_PORT_DATA_TYPE_INT,
	KERNEL_PORT_DATA_TYPE_SIZE_2D,
	KERNEL_PORT_DATA_TYPE_STRING,

	KERNEL_PORT_DATA_TYPE_FLOAT_ARRAY,
	KERNEL_PORT_DATA_TYPE_UNSIGNED_BYTE_ARRAY,

	KERNEL_PORT_DATA_TYPE_GL_BUFFER_OBJECT,
	KERNEL_PORT_DATA_TYPE_GL_TEXTURE_2D,
	KERNEL_PORT_DATA_TYPE_GL_TEXTURE_RECTANGLE,
	KERNEL_PORT_DATA_TYPE_GL_TEXTURE_RECTANGLE_ARRAY
};

#endif // KERNEL_PORT_DATA_TYPE_H
