// ==========================================================================
// SVM_GIST reads in K=3*512 dimensional feature descriptors for N
// scene and N' non-scene 256x256 images generated by COMPRESS_GIST.
// It then uses Davis King's DLIB library to load the input samples
// along with their positive and negative labels.  After the ordering
// of the input samples is randomized, cross-correlation is performed
// in order to estimate a reasonable value for a linear-SVM slack
// variable C.  DLIB then trains binary decision and probabilistic
// decision functions. Serialized versions of the binary and
// probabilistic decision functions are exported to output binary
// files.

// 				svm_gist

// ==========================================================================
// Last updated on 4/6/13 4/7/13; 4/14/13
// ==========================================================================


#include <fstream>
#include <iostream>
#include <string>
#include <vector>
#include <flann/flann.hpp>
#include <flann/io/hdf5.h>
#include "dlib/svm.h"

#include "astro_geo/Clock.h"
#include "general/filefuncs.h"
#include "general/outputfuncs.h"
#include "general/stringfuncs.h"
#include "general/sysfuncs.h"
#include "time/timefuncs.h"

using std::cin;
using std::cout;
using std::endl;
using std::flush;
using std::ifstream;
using std::ios;
using std::ofstream;
using std::string;
using std::vector;

using namespace dlib;

// ==========================================================================
int main(int argc, char *argv[])
// ==========================================================================
{
   std::set_new_handler(sysfunc::out_of_memory);

   const unsigned int K=3*512;

   string outdoor_categories_subdir="./all_images/training_images/";

   std::vector<string> scene;
   scene.push_back("coast");
   scene.push_back("forest");
   scene.push_back("highway");
   scene.push_back("insidecity");
   scene.push_back("mountain");
   scene.push_back("opencountry");
   scene.push_back("street");
   scene.push_back("tallbldg");

// Slack variables determined via cross validation on 4/14/13:

   std::vector<double> C_over_N;

   C_over_N.push_back(0.0152588);	// coast
   C_over_N.push_back(0.00976562);	// forest
   C_over_N.push_back(0.0238419);	// highway
   C_over_N.push_back(0.0238419);	// insidecity
   C_over_N.push_back(0.0298023);	// mountain
   C_over_N.push_back(0.0372529);	// opencountry
   C_over_N.push_back(0.0238419);	// street
   C_over_N.push_back(0.0190735);	// tallbldg

/*
// Slack variables determined via cross validation on 4/7/13:

   C_over_N.push_back(0.04656);	// coast
   C_over_N.push_back(0.03725);	// forest
   C_over_N.push_back(0.07275);	// highway
   C_over_N.push_back(0.01907);	// insidecity
   C_over_N.push_back(0.03725);	// mountain
   C_over_N.push_back(0.03029);	// opencountry
   C_over_N.push_back(0.03725);	// street
   C_over_N.push_back(0.02980);	// tallbldg
*/

   for (unsigned int scene_index=0; scene_index < scene.size(); scene_index++)
   {
      string curr_image_subdir=outdoor_categories_subdir+scene[scene_index]
         +"/";
      string gist_subdir=curr_image_subdir+"gist_files/";

      flann::Matrix<float> scene_descriptors,nonscene_descriptors;

// Import scene GIST descriptors:

      cout << "Loading scene descriptors" << endl;
      string scene_descriptors_hdf5_filename=gist_subdir+
         "scene_gist_descriptors.hdf5";
      cout << "scene_descrips_filename = "
           << scene_descriptors_hdf5_filename << endl;

      flann::load_from_file(
         scene_descriptors,scene_descriptors_hdf5_filename.c_str(),
         "gist_descriptors");

      cout << "scene_descriptors.rows = " << scene_descriptors.rows << endl;
      cout << "scene_descriptors.cols = " << scene_descriptors.cols << endl;
      unsigned int Nscene=scene_descriptors.rows;

// Limit number of scene descriptors for testing vs training purposes:

//      Nscene=400;

// Import non-scene GIST descriptors:
      
      cout << "Loading non-scene descriptors" << endl;

      string nonscene_descriptors_hdf5_filename=gist_subdir+
         "nonscene_gist_descriptors.hdf5";
      cout << "nonscene_desriptors_filename = "
           << nonscene_descriptors_hdf5_filename << endl;

      flann::load_from_file(
         nonscene_descriptors,nonscene_descriptors_hdf5_filename.c_str(),
         "gist_descriptors");

      cout << "nonscene_descriptors.rows = " << nonscene_descriptors.rows 
           << endl;
      cout << "nonscene_descriptors.cols = " << nonscene_descriptors.cols 
           << endl;
      unsigned int Nnonscene=nonscene_descriptors.rows;

// Define N as geometric mean of Nscene and Nnonscene:

      int N=sqrt(Nscene*Nnonscene);
      cout << "Nscene = " << Nscene << " Nnonscene = " << Nnonscene << endl;
      cout << "N = sqrt(Nscene*Nnonscene) = " << N << endl;
   
      double positive_to_negative_data_ratio=
         double(Nscene)/double(Nnonscene);
      cout << "Positive-to-negative data ratio = " 
           << positive_to_negative_data_ratio << endl;
   
      if (K != scene_descriptors.cols)
      {
         cout << "K = " << K 
              << " scene_descriptors.cols = " << scene_descriptors.cols
              << endl;
         exit(-1);
      }

// The svm functions use column vectors to contain a lot of the
// data on which they operate. So the first thing we do here is
// declare a convenient typedef.

// This typedef declares a matrix with K rows and 1 column.  It will
// be the object that contains each of our K dimensional samples. 

      typedef matrix<double, K, 1> sample_type;

// This is a typedef for the type of kernel we are going to use in
// this example.  In this case I have selected the linear kernel that
// can operate on our K-dim sample_type objects

      typedef linear_kernel<sample_type> kernel_type;


// On 10/11/12, we asked Davis for how to eventually work with much
// larger numbers of training samples than O(10**5).  He said that we
// basically must move towards working with sparse vectors.  Doing so
// will free up RAM and thereby increase the number of training
// samples we can input.  See svm_sparse_ex.cpp for the syntax for
// Davis' sparse vectors.  Also, the previous typedef will become

// 	typedef sparse_linear_kernel<sample_type> kernel_type

// [Davis also stressed that dotproducting input samples with
// dictionaries must be followed by some nonlinear threshold.  For
// Coates-Ng classification, the scalar nonlinear function is
// z=max{0,|Dx|-alpha} where alpha=0.5 . If no such nonlinear
// thresholding takes place, then linear classification with 9*N
// dictionary elements is mathematically equivalent to working with
// the initial image patch and not bothering with any dictionary
// dotproducting.]

// Now we make objects to contain our samples and their respective
// labels.

      std::vector<sample_type> samples;
      std::vector<double> labels;
      samples.reserve(Nscene+Nnonscene);
      labels.reserve(Nscene+Nnonscene);

      sample_type samp;

// Load gist data into samples and labels objects:

      for (unsigned int n=0; n<Nscene; n++)
      {
         for (unsigned int k=0; k<K; k++)
         {
            samp(k) = scene_descriptors[n][k];
            double val=scene_descriptors[n][k];
            if (val > POSITIVEINFINITY)
            {
               cout << "n = " << n << " k = " << k 
                    << " gist feature = " << scene_descriptors[n][k]
                    << endl;
            }
         }
         samples.push_back(samp);
         labels.push_back(1);
      } // loop over index n

// Load non-gist data into samples and labels objects:

      for (unsigned int n=0; n<Nnonscene; n++)
      {
         for (unsigned int k=0; k<K; k++)
         {
            samp(k) = nonscene_descriptors[n][k];
            double val=nonscene_descriptors[n][k];
            if (val > POSITIVEINFINITY)
            {
               cout << "n = " << n << " k = " << k 
                    << " nonscene feature = " << scene_descriptors[n][k]
                    << endl;
            }
         }
         samples.push_back(samp);
         labels.push_back(-1);
      } // loop over index n

// Here we normalize all the samples by subtracting their mean and
// dividing by their standard deviation. This is generally a good idea
// since it often heads off numerical stability problems and also
// prevents one large feature from smothering others.  Doing this
// doesn't matter much in this example so I'm just doing this here so
// you can see an easy way to accomplish this with the library.

      vector_normalizer<sample_type> normalizer;
      // let the normalizer learn the mean and standard deviation of the samples
      normalizer.train(samples);
      // now normalize each sample
      for (unsigned long i = 0; i < samples.size(); ++i)
      {
         samples[i] = normalizer(samples[i]); 
      }
   
// Now that we have some data we want to train on it.  However, there
// are two parameters to the training.  These are the nu and gamma
// parameters.  Our choice for these parameters will influence how
// good the resulting decision function is.  To test how good a
// particular choice of these parameters is we can use the
// cross_validate_trainer() function to perform n-fold cross
// validation on our training data.  However, there is a problem with
// the way we have sampled our distribution above.  The problem is
// that there is a definite ordering to the samples.  That is, the
// first half of the samples look like they are from a different
// distribution than the second half.  This would screw up the cross
// validation process but we can fix it by randomizing the order of
// the samples with the following function call.

      randomize_samples(samples, labels);

// Here we make an instance of the svm_c_linear_trainer object that uses our
// kernel type:

      svm_c_linear_trainer<kernel_type> trainer;
//   svm_c_ekm_trainer<kernel_type> trainer;

/*
// CROSS VALIDATION STARTS HERE:

      double min_C=0.004*N;
      double max_C=0.08*N;

// Now we loop over some different C values to see how good
// they are.  Note that this is a very simple way to try out a few
// possible parameter choices.  You should look at the
// model_selection_ex.cpp program for examples of more sophisticated
// strategies for determining good parameter choices.

      double max_product_correct=-1;
      double best_product_pos_correct,best_product_neg_correct;
      double max_sum_correct=-1;
      double best_sum_pos_correct,best_sum_neg_correct;
      double best_product_C,best_sum_C;

      cout << "Performing cross validation" << endl;
      for (double C = min_C; C < max_C; C *= 1.25)
//      for (double C = min_C; C < max_C; C *= 1.5)
//   for (double C = min_C; C < max_C; C *= 2)
      {
// tell the trainer the parameters we want to use

// If # class2/# class1 = alpha, then c_class1 = alpha c_class2 (rule
// of thumb)

         double C_positive=C;
         double C_negative=C*positive_to_negative_data_ratio;
         trainer.set_c_class1(C_positive);
         trainer.set_c_class2(C_negative);
         cout << "C_positive/N = " << C_positive/double(N)
              << " C_negative/N = " << C_negative/double(N) << endl;

// Print out the cross validation accuracy for 3-fold cross validation
// using the current C coeffient. cross_validate_trainer() returns a
// row vector.  The first element of the vector is the fraction of +1
// training examples correctly classified and the second number is the
// fraction of -1 training examples correctly classified.

         matrix<double,1,2> pos_neg_results=
            cross_validate_trainer(trainer,samples,labels,3);
         double pos_correct=pos_neg_results(0,0);
         double neg_correct=pos_neg_results(0,1);
         
         double product_correct=pos_correct*neg_correct;
         if (product_correct > max_product_correct)
         {
            max_product_correct=product_correct;
            best_product_pos_correct=pos_correct;
            best_product_neg_correct=neg_correct;
            best_product_C=C;
         }
         
         double sum_correct=pos_correct+neg_correct;
         if (sum_correct > max_sum_correct)
         {
            max_sum_correct=sum_correct;
            best_sum_pos_correct=pos_correct;
            best_sum_neg_correct=neg_correct;
            best_sum_C = C;
         }

         cout << "  Cross validation accuracy: " 
              << cross_validate_trainer(trainer, samples, labels, 3)
              << endl;
         cout << "  Product_correct = " << product_correct
              << " sum_correct = " << sum_correct << endl << endl;
      } // for loop over C

      cout << "max_product_correct = " << max_product_correct << endl;
      cout << "best_product_pos_correct = " << best_product_pos_correct 
           << endl;
      cout << "best_product_neg_correct = " << best_product_neg_correct 
           << endl;
      cout << "best_product_C = " << best_product_C << endl;
      cout << "best_product_C/N = " << best_product_C/N << endl;
      cout << endl;

      cout << "max_sum_correct = " << max_sum_correct << endl;
      cout << "best_sum_pos_correct = " << best_sum_pos_correct << endl;
      cout << "best_sum_neg_correct = " << best_sum_neg_correct << endl;
      cout << "best_sum_C = " << best_sum_C << endl;
      cout << "best_sum_C/N = " << best_sum_C/N << endl;

      outputfunc::enter_continue_char();
      continue;
//    exit(-1);

// After performing cross-validation on 500 positive and ~5000 negative
// on all 8 outdoor category images on 4/7/13, we found <C/N>=0.0354
// as the best average estimate for the linear SVM slack variable:

// CROSS VALIDATION ENDS HERE
*/

   double C=C_over_N[scene_index]*N;
      
   double C_positive=C;
   double C_negative=C*positive_to_negative_data_ratio;

   cout << "******************************************************" << endl;
   cout << "USING CROSS VALIDATION PARAMETERS C_POSITIVE = "
        << C_positive << " AND C_NEGATIVE = " << C_negative << endl;
   cout << "******************************************************" << endl;
   cout << endl;

//   trainer.set_c(C);

   trainer.set_c_class1(C_positive);
   trainer.set_c_class2(C_negative);

//   trainer.be_verbose();

// Now we train on the full set of data and obtain the resulting
// decision function.  The decision function will return values >= 0
// for samples it predicts are in the +1 class and numbers < 0 for
// samples it predicts to be in the -1 class.

   typedef decision_function<kernel_type> dec_funct_type;
   typedef normalized_function<dec_funct_type> funct_type;

// Here we are making an instance of the normalized_function object.
// This object provides a convenient way to store the vector
// normalization information along with the decision function we are
// going to learn.

   funct_type learned_function;
   learned_function.normalizer = normalizer;  // save normalization 
//   information

// Perform the actual SVM training and save the results.  Print out
// the number of support vectors in the resulting decision function:

   timefunc::initialize_timeofday_clock();
   cout << endl;
   cout << "-----------------------------------------------------" << endl;
   cout << "Starting to train binary decision function:" << endl;

   cout << "samples.size() = " << samples.size()
        << " labels.size() = " << labels.size() << endl;
   learned_function.function = trainer.train(samples, labels); 

   cout << "Elapsed time = " 
        << timefunc::elapsed_timeofday_time()/60 << " mins = " 
        << timefunc::elapsed_timeofday_time()/3600 << " hours" << endl;
   cout << "Number of support vectors in our learned_function =  " 
        << learned_function.function.basis_vectors.nr() << endl;
   cout << "Number of training samples: N = " << N << endl;

//   outputfunc::enter_continue_char();

// Another thing that is worth knowing is that just about everything
// in dlib is serializable. So for example, you can save the
// learned_pfunct object to disk and recall it later like so:

   string learned_funcs_subdir="./learned_functions/"+scene[scene_index]+"/";
   filefunc::dircreate(learned_funcs_subdir);

   string output_filename=learned_funcs_subdir+"symbols_Ng_bifunc.dat";
   ofstream fout(output_filename.c_str(),ios::binary);
   serialize(learned_function,fout);
   fout.close();

   string banner="Exported learned binary function to "+output_filename;
   outputfunc::write_banner(banner);

   Clock clock;
   clock.set_time_based_on_local_computer_clock();
   cout << "Current time: " << clock.YYYY_MM_DD_H_M_S() << endl;

// We can also train a decision function that reports a well
// conditioned probability instead of just a number > 0 for the +1
// class and < 0 for the -1 class.  An example of doing that follows:

   typedef probabilistic_decision_function<kernel_type> 
      probabilistic_funct_type;  
   typedef normalized_function<probabilistic_funct_type> pfunct_type;

   pfunct_type learned_pfunct; 
   learned_pfunct.normalizer = normalizer;

   timefunc::initialize_timeofday_clock();
   cout << endl;
   cout << "-----------------------------------------------------" << endl;
   cout << "Starting to train probabilistic decision function:" << endl;
   learned_pfunct.function = train_probabilistic_decision_function(
      trainer, samples, labels, 3);
   cout << "Elapsed time = " 
        << timefunc::elapsed_timeofday_time()/60 << " mins = " 
        << timefunc::elapsed_timeofday_time()/3600 << " hours" << endl;

// Now we have a function that returns the probability that a given
// sample is of the +1 class.

// print out the number of support vectors in the resulting decision
// function. (it should be the same as in the one above)

   cout << "Number of support vectors in our learned_pfunct =  " 
        << learned_pfunct.function.decision_funct.basis_vectors.nr() 
        << endl;
   cout << "Number of training samples: N = " << N << endl;

// Another thing that is worth knowing is that just about everything
// in dlib is serializable. So for example, you can save the
// learned_pfunct object to disk and recall it later like so:

   output_filename=learned_funcs_subdir+"symbols_Ng_pfunct.dat";
   ofstream fout2(output_filename.c_str(),ios::binary);
   serialize(learned_pfunct,fout2);
   fout2.close();

   banner="Exported learned probabilistic function to "+output_filename;
   outputfunc::write_banner(banner);

   clock.set_time_based_on_local_computer_clock();
   cout << "Current time: " << clock.YYYY_MM_DD_H_M_S() << endl;

// Now lets open that file back up and load the function object it
// contains:

   ifstream fin(output_filename.c_str(),ios::binary);
   deserialize(learned_pfunct, fin);

   cout << "Gist binary decision function = "
        << test_binary_decision_function(
           learned_function.function,samples,labels)
        << endl;

/*
// Note that there is also an example program that comes with dlib
// called the file_to_code_ex.cpp example.  It is a simple program
// that takes a file and outputs a piece of C++ code that is able to
// fully reproduce the file's contents in the form of a std::string
// object.  So you can use that along with the std::istringstream to
// save learned decision functions inside your actual C++ code files
// if you want.

// Lastly, note that the decision functions we trained above involved
// well over 200 basis vectors.  Support vector machines in general
// tend to find decision functions that involve a lot of basis
// vectors.  This is significant because the more basis vectors in a
// decision function, the longer it takes to classify new examples.
// So dlib provides the ability to find an approximation to the normal
// output of a trainer using fewer basis vectors.

// Here we determine the cross validation accuracy when we approximate
// the output using only 10 basis vectors.  To do this we use the
// reduced2() function.  It takes a trainer object and the number of
// basis vectors to use and returns a new trainer object that applies
// the necessary post processing during the creation of decision
// function objects.

cout << "Cross validation accuracy with only 10 support vectors: " 
<< cross_validate_trainer(reduced2(trainer,10), samples, labels, 3);

// Lets print out the original cross validation score too for
// comparison:

cout << "cross validation accuracy with all the original support vectors: " 
<< cross_validate_trainer(trainer, samples, labels, 3);

// When you run this program you should see that, for this problem,
// you can reduce the number of basis vectors down to 10 without
// hurting the cross validation accuracy.

// To get the reduced decision function out we would just do this:
learned_function.function = reduced2(trainer,10).train(samples, labels);

// And similarly for the probabilistic_decision_function: 

learned_pfunct.function = train_probabilistic_decision_function(
reduced2(trainer,10), samples, labels, 3);

cout << "Gist reduced binary decision function = "
<< test_binary_decision_function(
reduced2(null_trainer(learned_function.function), 50).train(
samples,labels),samples,labels)
<< endl;
*/

   } // loop over scene_index

}

