#!/bin/sh
# Hint: If the first INSERT fails, try mysql -u root mysql -e "describe host;" to check the structure of the host table

mysql -u root mysql << EOF
  DELETE FROM host WHERE Host='localhost' and Db='bookstore';
  INSERT INTO host VALUES
    ('localhost','%','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y');

  DELETE FROM user WHERE User='bookuser';

  INSERT INTO user (Host,User,Password,Select_priv,Insert_priv,Update_priv,Delete_priv,Create_priv,Drop_priv,Reload_priv,Shutdown_priv,Process_priv,File_priv,Grant_priv,References_priv,Index_priv,Alter_priv,Show_db_priv,Super_priv,Create_tmp_table_priv,Lock_tables_priv,Execute_priv,Repl_slave_priv,Repl_client_priv) VALUES ('localhost', 'bookuser', PASSWORD('bookpass'),'Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y');

  flush privileges;
EOF
