// ==========================================================================
// Program REMOVE_LEADING_WHITESPACE is a specialized utility which we
// wrote in order to eliminate a leading space that appeared in the
// filenames for CSV mask files generated by Joe Isaacson in Nov 2012.
// ==========================================================================
// Last updated on 11/30/12
// ==========================================================================

#include  <iostream>
#include  <string>
#include  <vector>

#include "general/filefuncs.h"
#include "general/stringfuncs.h"
#include "general/sysfuncs.h"

using std::cin;
using std::cout;
using std::endl;
using std::string;
using std::vector;

int main(int argc, char* argv[])
{
   cout.precision(12);

   string subdir="./";
   vector<string> input_filenames=filefunc::files_in_subdir(subdir);
   for (int i=0; i<input_filenames.size(); i++)
   {
      string dirname=filefunc::getdirname(input_filenames[i]);
      string basename=filefunc::getbasename(input_filenames[i]);
      string white_space=stringfunc::return_leading_whitespace(basename);

      string orig_filename=dirname;
      if (white_space.size() > 0)
      {
         orig_filename += "\\";
      }
      orig_filename += basename;

      string cleaned_filename=dirname+
         stringfunc::remove_leading_whitespace(basename);
      string unix_cmd="mv "+orig_filename+" "+cleaned_filename;
      cout << unix_cmd << endl;
      sysfunc::unix_command(unix_cmd);
   }


}

