SOURCES	+= filechooser.cpp main.cpp 
HEADERS	+= filechooser.h 
TARGET		= filechooser
TEMPLATE	=app
CONFIG	+= qt warn_on release
DBFILE	= filechooser.db
PROJECTNAME	= Filechooser
LANGUAGE	= C++
unix:MOC_DIR = .moc
unix:OBJECTS_DIR = .obj
